name: Build & Deploy - NextJS App

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, "ready_for_review"]
    # paths:
    #   nextjs-app/**

  push:
    branches:
      - main

concurrency:
  group: CI-NextJS-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build-deploy-next-app:
      name: Build & Deploy - nextjs-app
      uses: ./.github/workflows/build-deploy.yml
      with:
          amplify-app-id: 'd1106vmj1ozg8d'
          package-name: 'nextjs-app'
          package-dist-directory: './nextjs-app/out'
          bucket-name-preview: 'pie-aperture-preview'
          bucket-name-main: 'pie-aperture'
      secrets: inherit

  browser-tests:
    needs: 'build-deploy-next-app'
    name: Run WebDriverIO Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies - Root
        shell: bash
        run: yarn
  
      - name: Install Dependencies - NextJS App
        shell: bash
        working-directory: ./nextjs-app
        run: yarn

      - name: Run WebDriverIO Tests
        shell: bash
        run: yarn wdio:nextjs
    env:
      PR_NUMBER: ${{ github.event.number }}
      NEXT_AMPLIFY_ID: d1106vmj1ozg8d
